apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: petclinic-app=docker.home.local/petclinic:latest
    argocd-image-updater.argoproj.io/petclinic-app.update-strategy: newest-build
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main 
    argocd-image-updater.argoproj.io/petclinic-app.force-update: "true"
spec:
  project: default
  source:
    repoURL: 'https://github.com/vladoz77/petclinic-cd.git'
    path: petclinic-app
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petclinic
  syncPolicy:
    automated: 
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
