apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: petclinic
patchesStrategicMerge:
  - prod-deployment.yaml
commonLabels:
  stage: prod
