apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-app
spec:
  replicas: 3
  template:
    spec:
      containers:
        - image: vladoz77/petclinic:1.0.0-366
          name: petclinic
