apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petclinic-app
  name: petclinic-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - image: vladoz77/petclinic:1.0.0-366
        name: petclinic
        resources: {} 
          # requests:
          #   memory: 400Mi
          #   cpu: 100m
          # limits:
          #   memory: 500Mi
          #   cpu: 200m
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5

        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          timeoutSeconds: 5
        ports:
          - name: app
            containerPort: 8080
      

          
