apiVersion: v1
kind: Secret
metadata:
  name: nexus-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXIuaG9tZS5sb2NhbCI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZJVkZCV2pKM2MzZz0iCgkJfSwKCQkiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewoJCQkiYXV0aCI6ICJkbXhoWkc5Nk56YzZWbXhBWkRCNk56ZFdTdz09IgoJCX0sCgkJIm5leHVzLmhvbWUubG9jYWwiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2SVZGQldqSjNjM2c9IgoJCX0sCgkJInByb3h5LmhvbWUubG9jYWwiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2SVZGQldqSjNjM2c9IgoJCX0sCgkJInJlZy5ob21lLmxvY2FsIjogewoJCQkiYXV0aCI6ICJhMjkyWVd4bGRqb2hVVUZhTW5kemVBPT0iCgkJfQoJfQp9

