apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-petclinic-dep.yaml
- 02-petclinic-svc.yaml
images:
- name: vladoz77/petclinic
  digest: sha256:57923c85fa06cbd5f6c9cda76f6eafd94acacb230a0a95d02c5df71466de1f7f
